---
- name: remove env file if exists
  ansible.builtin.file:
    path: /usr/share/docker/gun/.env
    state: absent

- name: create gun env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/gun/.env
    create: yes
    marker: '# {mark} Ansible set environment'
    block: |
      DOMAIN_NAME={{ domain_name }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      COMPOSE_PROJECT_NAME=gun

- name: place gun docker-compose file in the right directory
  copy:
    src: roles/gun/files/
    dest: /usr/share/docker/gun/

- name: start gun container
  community.docker.docker_compose:
    project_src: /usr/share/docker/gun
    build: true
    state: present