version: "3.9"

services:
  master:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    ports:
      - 9333:9333
      - 19333:19333
    volumes:
      - seaweed_master_metadata:/mnt/metadata:rw
      - seaweed_master_data:/data
      - ./security.toml:/security.toml
    command:
      [
        master,
        -ip=master,
        -ip.bind=0.0.0.0,
        -port=9333,
        -volumeSizeLimitMB=4096,
        -metricsPort=9999,
        -volumePreallocate,
        -mdir=/mnt/metadata,
      ]

  volume:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    ports:
      - 8080:8080
      - 18080:18080
    command:
      [
        volume,
        -mserver=master:9333,
        -ip.bind=0.0.0.0,
        -port=8080,
        -ip=$DOMAIN_NAME,
        -max=5,
        -preStopSeconds=1,
      ]
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    command: [filer, -master=master:9333, -ip=$DOMAIN_NAME, -ip.bind=0.0.0.0, -metricsPort=9326]
    tty: true
    stdin_open: true
    depends_on:
      - master
      - volume

  s3:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    ports:
      - 8333:8333
      - 9327:9327
    command: [s3 -filer=filer:8888 -ip=$DOMAIN_NAME, -ip.bind=0.0.0.0 -metricsPort=9327]
    depends_on:
      - master
      - volume
      - filer

  prometheus:
    image: prom/prometheus:v2.21.0
    restart: unless-stopped
    ports:
      - 9991:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - s3

volumes:
  seaweed_master_data:
  seaweed_master_metadata:
