---
- name: create openldap env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/openldap/.env
    create: yes
    marker: '#{mark} Ansible set environment'
    block: |
      HOSTNAME={{ hostname }}

      LDAP_ADD_SCHEMAS={{ openldap.add_schemas }}
      LDAP_ADMIN_PASSWORD={{ secrets.openldap.admin_password }}
      LDAP_ADMIN_USERNAME={{ openldap.admin_username }}
      LDAP_EXTRA_SCHEMAS={{ openldap.extra_schemas }}
      LDAP_GROUP={{ openldap.group }}
      LDAP_PASSWORDS={{ secrets.openldap.passwords }}
      LDAP_PORT_NUMBER={{ openldap.port_number }}
      LDAP_ROOT={{ openldap.base_dn }}
      LDAP_USER_DC={{ openldap.user_dc }}
      LDAP_USERS={{ openldap.users }}

      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}

- name: create openldap volume
  community.docker.docker_volume:
    name: openldap_data

- name: create ldap network
  community.docker.docker_network:
    name: ldap

- name: place openldap docker-compose file in the right directory
  copy:
    src: roles/openldap/files/docker-compose.yml
    dest: /usr/share/docker/openldap/docker-compose.yml

- name: place openldap ldif directory
  copy:
    src: roles/openldap/files/ldifs/
    dest: /usr/share/docker/openldap/ldifs

- name: start openldap container
  community.docker.docker_compose:
    project_src: /usr/share/docker/openldap
    state: present