---
- name: set DOCKER_HOST environment variable
  lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^DOCKER_HOST="
    line: "DOCKER_HOST=unix:///run/podman/podman.sock"

- name: Install Podman
  become: true
  apt:
    name:
      - podman
      - python3
      - python3-pip
    state: latest

- name: copy daemon.json file
  copy:
    src: roles/docker_debian/files/registries.conf
    dest: /etc/containers/registries.conf
