version: "3"

services:
  gun_server:
    image: gun
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - gunData:/home/node/gun
    ports:
      - 8765:8765
    networks:
      - traefik
    labels: 
      - traefik.enable=true
      - traefik.http.routers.gun.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.gun.rule=Host(`gun.${DOMAIN_NAME}`)
      - traefik.http.routers.gun_secure.rule=Host(`gun.${DOMAIN_NAME}`)
      - traefik.http.routers.gun_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.gun_secure.tls.certresolver=le_staging
      - traefik.http.services.gun.loadbalancer.server.port=8765

volumes:
  gunData:

networks:
  traefik:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true
    