- block:
    - name: install requirements
      ansible.builtin.apt:
        update_cache: true
        name:
          - gnupg2
          - ca-certificates
          - curl
          - python3-full
          - virtualenv

    - name: add key for docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg

    - name: add repository for docker
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
        state: present

    - name: install docker-ce and docker compose
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: create docker group
      ansible.builtin.group:
        name: docker

    - name: add docker group to user
      ansible.builtin.user:
        name: '{{ ansible_user_id }}'
        groups: docker
        append: true

  become: true
