---
- name: Check if Docker is installed
  become: true
  command: docker -v 
  register: docker_installed
  ignore_errors: true

- name: Install Docker 
  become: true
  block:
    - name: Add Docker's official GPG key
      become: true
      block:
        - name: Install necessary packages
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg2
              - software-properties-common
            state: latest
            update_cache: true

        - name: Add GPG key
          apt_key:
            url: https://download.docker.com/linux/debian/gpg
            state: present

    - name: Add the repository to Apt sources
      block:
        - name: Get sytem architecture 
          shell:
            cmd: echo "$(dpkg --print-architecture)"
          register: ARCHITECTURE 

        - name: Get OS release name
          shell:
            cmd: echo "$(. /etc/os-release && echo "$VERSION_CODENAME")"
          register: OS_RELEASE 

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch={{ ARCHITECTURE.stdout_lines[0] }}]  https://download.docker.com/linux/debian {{ OS_RELEASE.stdout_lines[0] }} stable
            state: present

    - name: Install Docker packages
      become: true
      apt:
        name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: latest
        update_cache: true
  when: docker_installed.failed