services:
  directus:
    #image: directus/directus:11.1.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${DIRECTUS_PORT}:8055
    networks:
      - bundes_postgres
    #volumes:
    #- directus_database:/directus/database
    #- directus_uploads:/directus/uploads
    #- directus_extensions:/directus/extensions
    environment:
      MARKETPLACE_TRUST: all

      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      #DB_CLIENT: 'sqlite3'
      #DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: 'true'

      DB_CLIENT: ${DB_CLIENT:-pg}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-directus}
      DB_USER: ${DB_USER:-directus}
      DB_PASSWORD: ${DB_PASSWORD:-directus}

      ACCESS_TOKEN_TTL: 15m
      CORS_ENABLED: true
      CORS_ORIGIN: true
volumes:
  #directus_database:
  directus_uploads:
  directus_extensions:

networks:
  bundes_postgres:
    external: true
