---
- name: remove env file if exists
  ansible.builtin.file:
    path: /usr/share/docker/keycloak/.env
    state: absent
    
- name: create keycloak env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/keycloak/.env
    create: yes
    marker: '# {mark} Ansible set environment'
    block: |
      DOMAIN_NAME={{ domain_name }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      KEYCLOAK_NETWORK_NAME={{ keycloak.network_name }}

- name: place keycloak files in the right directory
  copy:
    src: roles/keycloak/files/
    dest: /usr/share/docker/keycloak/
    
- name: start keycloak container
  community.docker.docker_compose:
    project_src: /usr/share/docker/keycloak
    state: present