version: "3.7"
services:
  kratos-migrate:
    image: oryd/kratos:v1.1.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    command: --config /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    depends_on:
      - kratos
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      #- KRATOS_BROWSER_URL=http://${DOMAIN_NAME}:4433/
      #- PORT=${KRATOS_SELFSERVICE_PORT}
      #- SECURITY_MODE=

      - COOKIE_SECRET=lnawdhsaeudiw3r9w3r9u40t8402hjwjks
      - CSRF_COOKIE_NAME=kratos_ui
      - CSRF_COOKIE_SECRET=28349283uhfkjliaukjyslöaj

      # oathkeeper
      - PORT=${KRATOS_SELFSERVICE_PORT}
      - KRATOS_BROWSER_URL=http://auth.${DOMAIN_NAME}:80/.ory/kratos/public
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
    networks:
      - intranet
    ports:
      - ${KRATOS_SELFSERVICE_PORT}:${KRATOS_SELFSERVICE_PORT}
    restart: on-failure

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    ports:
      - 4455:4455
      - 4456:4456
    command: serve proxy --config "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - traefik
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper
    labels:
      traefik.enable: true

      #traefik.http.routers.oathkeeper.entryPoints: ${TRAEFIK_ENDPOINT_HTTP_NAME:-web}
      #traefik.http.routers.oathkeeper.rule: Host(`auth.${DOMAIN_NAME}`)
      #traefik.http.services.oathkeeper.loadbalancer.server.port: 4455

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace

      # oathkeeper
      - SERVE_PUBLIC_BASE_URL=http://auth.${DOMAIN_NAME}:80/.ory/kratos/public/
    command: serve --config /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./config
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

networks:
  intranet:
  traefik:
    name: ${TRAEFIK_NETWORK_NAME:-proxy}
    external: true

volumes:
  kratos-sqlite:
