version: "3"

services:
  heimdall:
    image: linuxserver/heimdall
    ports:
      - 3380:80 
    networks:
      - web
    environment:
      - PGID=1000  
      - PUID=1000
    labels: 
      - traefik.enable=true
      - traefik.http.routers.heimdall.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.heimdall.rule=Host(`heimdall.${HOSTNAME}`)
      - traefik.http.routers.heimdall_secure.rule=Host(`heimdall.${HOSTNAME}`)
      - traefik.http.routers.heimdall_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.heimdall_secure.tls.certresolver=le_staging
      - traefik.http.services.heimdall.loadbalancer.server.port=80

networks:
  web:
    external: true
      