---
- name: deploy services on haex space
  hosts: haex.space
  vars_files:
    - secrets.yml
  become: true
  roles:
    #- docker
    #- users/haex
    #- vim
    #- ssh
    #- cos
    #- supabase
    #- nhost
    # - gitlab
    #- seafile
    #- cos
    #- supabase
    #- nhost
    #- heimdall
    #- gitlab
    - traefik
    - portainer
    - gun