---
- name: install docker
  hosts: haex.space
  vars_files:
    - secrets.yml
  become: true
  roles:
    # - portainer
    # - lldap
    # - docker
    # - users/haex
    # - vim
    # - ssh
    # - traefik
    - openldap
    - seafile
