---
- name: deploy an haex space
  hosts: haex.space
  #vars_files:
  #  - secrets.yml
  become: true
  roles:
    #- portainer
    #- lldap
    #- docker
    #- users/haex
    #- vim
    #- ssh
    #- traefik
    #- openldap
    #- seafile
    #- bitwarden
    #- cos
    #- supabase
    #- nhost
    #- heimdall
    #- keycloak
    - gitlab
