---
- name: deploy services on haex space
  hosts: haex.space
  vars_files:
    - secrets.yml
  vars:
    domain_name: haex.space
    mode: development # development or production or localhost
    from_scratch: false

  roles:
    - docker_debian
    - nodejs_debian
    - vim_debian
    - traefik
    - portainer
    - postgres
    - directus
