---
- name: deploy services on haex space
  hosts: haex.space
  vars_files:
    - secrets.yml
  become: true
  roles:
    #- portainer
    #- docker
    #- users/haex
    #- vim
    #- ssh
    - traefik
    #- cos
    #- supabase
    #- nhost
    - keycloak
    # - gitlab
