---
- name: deploy services on haex space
  hosts: haex.space
  vars_files:
    - secrets.yml
  become: true
  roles:
    #- docker_debian
    #- vim_debian
    - traefik
    #- authelia
    - portainer
    #- vaultwarden
    #- rustdesk
    #- seafile
    #- homarr
    #- jellyfin
    #- seaweed
    - kratos
