---
- name: deploy services on haex space
  hosts: haex.space
  vars_files:
    - secrets.yml
  vars:
    domain_name: haex.space
    mode: production # development or production or localhost
    from_scratch: false
  environment:
    ANSIBLE_DEBUG: 1

  roles:
    # - docker_debian
    # - nodejs_debian
    # - vim_debian
    # - traefik
    # - portainer
    # - postgres
    # - nocodb
    # - gitea
    # - directus
    # - haexspace
    - n8n
