- name: deploy services on localhost
  hosts: localhost
  connection: local
  vars_files:
    - secrets.yml

  vars:
    domain_name: localhost
    mode: localhost # development or production or localhost
    from_scratch: false

  roles:
    #- vim_debian
    #- postgres
    - portainer
    #- directus

  tasks:
    - name: show vars
      ansible.builtin.debug:
        msg:
          - 'set vars: {{ vars.postgres }}'
    - name: debug
      ansible.builtin.shell: 'id -u ${whoami}'
      register: 'output'

    - debug:
        msg: '{{ output.stdout_lines }}'
