---
- name: prepare directus for {{ mode }}
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - from_scratch.yml
    - copy_files.yml
    - create_env_file.localhost.yml
    - set_params_directus_sync_file.yml
    - start_container.yml
    - sync_directus.yml
  when: mode == "localhost"

- name: prepare directus for {{ mode }}
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - from_scratch.yml
    - copy_files.yml
    - create_env_file.yml
    - set_params_directus_sync_file.yml
    - start_container.yml
    - sync_directus.yml
  when: mode != "localhost"
