- name: wait for directus is up and running
  ansible.builtin.wait_for:
    port: '8055'
    delay: 10

- name: Sync directus instance
  ansible.builtin.command:
    chdir: '{{ directus.root_directory }}'
    cmd: 'npx directus-sync push'
