---
- name: create lldap env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/lldap/.env
    create: yes
    marker: '#{mark} Ansible set environment'
    block: |
      HOSTNAME={{ hostname }}
      LLDAP_UID={{ lldap.uid }}
      LLDAP_GID={{ lldap.gid }}
      LLDAP_JWT_SECRET={{ secrets.lldap.lldap_jwt_secret}}
      LLDAP_LDAP_USER_PASS={{ secrets.lldap.lldap_ldap_user_pass }}
      LLDAP_LDAP_BASE_DN='{{ lldap.base_dn }}'
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}

- name: create lldap volume
  community.docker.docker_volume:
    name: lldap_data

- name: set uid and gid of lldap volume
  file:
    path: /var/lib/docker/volumes/lldap_data/_data
    owner: "{{ lldap.uid }}"
    group: "{{ lldap.gid }}"
    recurse: yes

- name: place lldap docker-compose file in the right directory
  copy:
    src: roles/lldap/files/docker-compose.yml
    dest: /usr/share/docker/lldap/docker-compose.yml
    
- name: start lldap container
  community.docker.docker_compose:
    project_src: /usr/share/docker/lldap
    state: present