version: "3.8"
services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge_data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - dockge_stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
    labels:
      traefik.enable: true
      traefik.docker.network: ${TRAEFIK_NETWORK_NAME:-proxy}
      #traefik.http.routers.dockge.entrypoints: ${TRAEFIK_HTTP_ENDPOINT}
      #traefik.http.routers.dockge.rule: Host(`dockge.${DOMAIN_NAME}`)
      traefik.http.routers.dockge_secure.rule: Host(`dockge.${DOMAIN_NAME}`)
      traefik.http.routers.dockge_secure.entrypoints: ${TRAEFIK_HTTPS_ENDPOINT}
      traefik.http.routers.dockge_secure.tls.certresolver: ${TRAEFIK_LETS_ENCRYPT_RESOLVER:-http_resolver_staging}
      traefik.http.services.dockge.loadbalancer.server.port: 5001

volumes:
  dockge_data:
  dockge_stacks:

networks:
  traefik:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true
