version: '3.7'

services: 
  isogit:
    restart: unless-stopped
    build: 
      context: /usr/share/docker/isogit
      dockerfile: Dockerfile
    container_name: isogit
    hostname: isogit
    networks:
      - web
    ports: 
      - 127.0.0.1:3434:8080
    labels: 
      - traefik.enable=true
      - traefik.http.routers.isogit.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.isogit.rule=Host(`isogit.${HOSTNAME}`)
      - traefik.http.routers.isogit_secure.rule=Host(`isogit.${HOSTNAME}`)
      - traefik.http.routers.isogit_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.isogit_secure.tls.certresolver=le
      - traefik.http.services.isogit.loadbalancer.server.port=8080

networks: 
 web:
    name: web
    external: true