- name: Check if .env file exists
  ansible.builtin.stat:
    path: "{{ bundesgesetze.root_directory }}/.env"
  register: env_file

- name: create portainer env file
  ansible.builtin.blockinfile:
    path: "{{ bundesgesetze.root_directory }}/.env"
    create: true
    marker: "# {mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      SUB_DOMAIN_NAME={{ bundesgesetze.sub_domain_name }}
  when: not env_file.stat.exists
