---
- name: check if bundesgesetze directory exists
  ansible.builtin.stat:
    path: "{{ bundesgesetze.root_directory }}"
  register: bundesgesetze_directory

- name: remove bundesgesetze folder and env file if exists
  block:
    - name: stop bundesgesetze stack
      community.docker.docker_compose_v2:
        project_src: "{{ bundesgesetze.root_directory }}"
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: "{{ bundesgesetze.root_directory }}"
        state: absent
  when: bundesgesetze_directory.stat.exists and (bundesgesetze.from_scratch == true or from_scratch == true)
