---
- name: check if portainer directory exists
  ansible.builtin.stat:
    path: /usr/share/docker/portainer
  register: portainer_directory

- name: remove portainer folder and env file if exists
  block:
    - name: stop portainer stack
      community.docker.docker_compose_v2:
        project_src: /usr/share/docker/portainer
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: /usr/share/docker/portainer
        state: absent
  when: portainer_directory.stat.exists and (portainer.from_scratch == true or from_scratch == true)
