---
- name: prepare bundesgesetze for {{ mode }}
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - from_scratch.yml
    - place_files_and_folders.yml
    - create_env_file.localhost.yml
    - start_container.yml
    - prepare_and_run_import.yml
  when: mode == "localhost"

- name: prepare bundesgesetze for {{ mode }}
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - from_scratch.yml
    - place_files_and_folders.yml
    - create_env_file.yml
    - start_container.yml
    - prepare_and_run_import.yml
  when: mode != "localhost"
