- name: copy Dockerfile file
  ansible.builtin.copy:
    src: roles/haexspace/files/Dockerfile
    dest: '{{ haexspace.app_directory }}/Dockerfile'

- name: copy localhost compose file
  ansible.builtin.copy:
    src: roles/haexspace/files/docker-compose.localhost.yml
    dest: '{{ haexspace.app_directory }}/docker-compose.yml'
  when: mode == "localhost"

- name: copy compose file
  ansible.builtin.copy:
    src: roles/haexspace/files/docker-compose.yml
    dest: '{{ haexspace.app_directory }}/docker-compose.yml'
  when: mode != "localhost"
