---
- name: check if haexspace directory exists
  ansible.builtin.stat:
    path: '{{ haexspace.app_directory }}'
  register: haexspace_directory

- name: remove haexspace folder and env file if exists
  block:
    - name: stop haexspace stack
      community.docker.docker_compose_v2:
        project_src: '{{ haexspace.app_directory }}'
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: '{{ haexspace.app_directory }}'
        state: absent
  when: haexspace_directory.stat.exists and (haexspace.from_scratch == true or from_scratch == true)

- name: create app directory
  ansible.builtin.file:
    path: '{{ haexspace.app_directory }}'
    state: directory
