haex_space:
  hosts:
    haex.space:

  vars:
    mode: development # development or production
    domain_name: haex.space
    app_directory: '~/apps'

    traefik:
      from_scratch: false
      container_name: traefik
      hostname: traefik
      sub_domain_name: traefik
      app_directory: '{{ app_directory }}/traefik'
      endpoint:
        http:
          name: web
          port: 80
        https:
          name: web_secure
          port: 443
        ping:
          name: ping
          port: 88
      image_version: latest
      image: traefik
      lets_encrypt:
        email: hexxx@ok.de
        storage:
          http_resolver: /acme_letsencrypt.json # absolute path needed
          tls_resolver: /tls_letsencrypt.json # absolute path needed
      network_name: proxy

    crowdsec:
      container_name: crowdsec
      hostname: crowdsec
      image_version: latest
      image: crowdsecurity/crowdsec
      networks_crowdsec_ipv4: 172.31.254.254

    traefik_crowdsec_bouncer:
      container_name: traefik_crowdsec_bouncer
      hostname: traefik-crowdsec-bouncer
      image: fbonalair/traefik-crowdsec-bouncer
      image_version: latest
      networks_crowdsec_ipv4: 172.31.254.252

    networks:
      proxy_name: proxy
      proxy_subnet_ipv4: 172.30.0.0/16
      crowdsec_name: crowdsec
      crowdsec_subnet_ipv4: 172.31.0.0/16

    portainer:
      from_scratch: false
      app_directory: '{{ vars.app_directory }}/portainer'
      sub_domain_name: portainer

    postgres:
      from_scratch: false
      app_directory: '{{ app_directory }}/postgres'

    directus:
      from_scratch: false

      app_directory: '{{ app_directory }}/directus'
      sub_domain_name: directus
      protocol: 'http'

      directus_port: 8055

      db_client: 'pg'
      db_database: 'postgres'
      db_host: 'postgres'
      db_port: 5432
      db_user: 'postgres'

    nodejs:
      version: 20

    haexspace:
      from_scratch: true
      app_directory: '{{ app_directory }}/haexspace'
      sub_domain_name: haexspace
