haex_space:
  hosts:
    haex.space: 

  vars:
    domain_name: haex.space

    traefik:
      container_name: traefik
      hostname: traefik
      http_endpoint: web
      https_endpoint: websecure
      image: traefik
      image_version: latest
      labels_traefik_host: traefik.haex.space
      network_name: proxy
      networks_crowdsec_ipv4: 172.31.254.253
      networks_proxy_ipv4: 172.30.255.254
      lets_encrypt: {
        email: hexxx@ok.de,
        storage: {
          http_resolver: acme_letsencrypt.json,
          tls_resolver: tls_letsencrypt.json
        }
      }

    crowdsec:
      container_name: crowdsec
      hostname: crowdsec
      image_version: latest
      image: crowdsecurity/crowdsec
      networks_crowdsec_ipv4: 172.31.254.254

    traefik_crowdsec_bouncer:
      container_name: traefik_crowdsec_bouncer
      hostname: traefik-crowdsec-bouncer
      image: fbonalair/traefik-crowdsec-bouncer
      image_version: latest
      networks_crowdsec_ipv4: 172.31.254.252

    networks:
      proxy_name: proxy
      proxy_subnet_ipv4: 172.30.0.0/16
      crowdsec_name: crowdsec
      crowdsec_subnet_ipv4: 172.31.0.0/16