haex_space:
  hosts:
    haex.space: 

  vars:
    domain_name: haex.space

    traefik:
      container_name: traefik
      hostname: traefik
      http_endpoint: http
      https_endpoint: https
      image_version: 2.10
      labels_traefik_host: traefik.haex.space
      network_name: traefik
      networks_crowdsec_ipv4: 172.31.254.253
      networks_proxy_ipv4: 172.30.255.254
      
    crowdsec:
      container_name: crowdsec
      hostname: crowdsec
      image_version: latest
      image: crowdsecurity/crowdsec
      networks_crowdsec_ipv4: 172.31.254.254

    traefik_crowdsec_bouncer:
      container_name: traefik_crowdsec_bouncer
      hostname: traefik-crowdsec-bouncer
      image: fbonalair/traefik-crowdsec-bouncer
      image_version: latest
      networks_crowdsec_ipv4: 172.31.254.252

    networks:
      proxy_name: proxy
      proxy_subnet_ipv4: 172.30.0.0/16
      crowdsec_name: crowdsec
      crowdsec_subnet_ipv4: 172.31.0.0/16