haex_space:
  hosts:
    haex.space:

  vars:
    mode: development # development or production
    domain_name: haex.space
    app_directory: "~/apps"

    traefik:
      from_scratch: false
      container_name: traefik
      hostname: traefik
      sub_domain_name: traefik
      app_directory: "{{ app_directory }}/traefik"
      endpoint:
        http:
          name: web
          port: 80
        https:
          name: web_secure
          port: 443
        ping:
          name: ping
          port: 88
      image_version: latest
      image: traefik
      lets_encrypt:
        email: hexxx@ok.de
        storage:
          http_resolver: /acme_letsencrypt.json # absolute path needed
          tls_resolver: /tls_letsencrypt.json # absolute path needed
      network_name: proxy

    networks:
      proxy_name: proxy
      proxy_subnet_ipv4: 172.30.0.0/16
      crowdsec_name: crowdsec
      crowdsec_subnet_ipv4: 172.31.0.0/16

    portainer:
      from_scratch: false
      app_directory: "{{ app_directory }}/portainer"
      sub_domain_name: portainer

    postgres:
      from_scratch: false
      app_directory: "{{ app_directory }}/postgres"
      image: postgres
      image_tag: alpine

    haexspace:
      from_scratch: true
      app_directory: "{{ app_directory }}/haexspace"
      sub_domain_name: haexspace

    gitea:
      from_scratch: true
      app_directory: "{{ app_directory }}/gitea"
      sub_domain_name: git
      image_tag: latest-rootless
      image: docker.gitea.com/gitea
