halunken_space:
  hosts:
    halunken.space:

  vars:
    mode: development # development or production
    domain_name: halunken.space

    traefik:
      container_name: traefik
      hostname: traefik
      sub_domain: traefik
      http_endpoint: web
      https_endpoint: web_secure
      image_version: latest
      image: traefik
      lets_encrypt:
        email: hexxx@ok.de
        storage:
          http_resolver: /acme_letsencrypt.json
          tls_resolver: /tls_letsencrypt.json
      network_name: proxy
      ping_port: 88
      http_port: 80
      https_port: 433

    seaweed:
      cors:
        allowed:
          origins: "*"

    authelia:
      sub_domain: auth
      default_redirection_url: https://halunken.space
      notifier:
        smtp:
          host: smtp.ok.de
          port: 587
          sender: hexxx@ok.de
          username: martin.drechsel@ok.de
