halunken_space:
  hosts:
    halunken.space:

  vars:
    mode: development # development or production
    domain_name: halunken.space

    traefik:
      container_name: traefik
      hostname: traefik
      sub_domain: traefik
      http_endpoint: web
      https_endpoint: web_secure
      image_version: latest
      image: traefik
      lets_encrypt:
        storage:
          http_resolver: /acme_letsencrypt.json
          tls_resolver: /tls_letsencrypt.json
      network_name: proxy
      ping_port: 88
      http_port: 80
      https_port: 433

    bundesgestze:
      sub_domain_name: bundesgesetze
