local:
  hosts:
    localhost:

  vars:
    domain_name: localhost
    mode: localhost # development or production or localhost
    app_directory: '~/apps'

    portainer:
      from_scratch: true

      app_directory: '{{ vars.app_directory }}/portainer'
      sub_domain_name: portainer

    postgres:
      from_scratch: true

      app_directory: '{{ app_directory }}/postgres'

    directus:
      from_scratch: true

      app_directory: '{{ app_directory }}/directus'
      sub_domain_name: directus
      protocol: 'http'

      directus_port: 8055

      db_client: 'pg'
      db_database: 'postgres'
      db_host: 'postgres'
      db_port: 5432
      db_user: 'postgres'
