services:
  seafile-db:
    image: mariadb:10.6
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./mysql-db:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: unless-stopped
    volumes:
      - seafile_data:/shared
    environment:
      - DB_HOST=seafile-db
      - DB_ROOT_PASSWD=db_dev
      - TIME_ZONE=Europe/Berlin
      - SEAFILE_ADMIN_EMAIL=hexxx@ok.de
      - SEAFILE_ADMIN_PASSWORD=test
      - SEAFILE_SERVER_LETSENCRYPT=false
      - FORCE_HTTPS_IN_CONF=true
      - SEAFILE_SERVER_HOSTNAME=seafile.haex.space
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.seafile.entrypoints=websecure"
      - "traefik.http.routers.seafile.rule=(Host(`seafile.haex.space`))"
      - "traefik.http.routers.seafile.tls=true"
      - "traefik.http.routers.seafile.tls.certresolver=http_resolver_staging"
      - "traefik.http.routers.seafile.service=seafile"
      - "traefik.http.services.seafile.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.seafile.middlewares=authelia@docker"
      # - "traefik.http.routers.seafile.middlewares=default@file"

    depends_on:
      - seafile-db
      - memcached
    networks:
      - seafile-net
      - proxy

networks:
  seafile-net:
  proxy:
    external: true

volumes:
  seafile_data:
