version: '3'
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${SEAFILE_DB_ROOT_PASSWORD}  # Requested, set the root's password of MySQL service.
      - MYSQL_ROOT_PASSWORD=${SEAFILE_DB_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - seafile_mysql:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:latest
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    restart: unless-stopped
    ports:
      - "2080:80"
     # - "12443:443"  # If https is enabled, cancel the comment.
    volumes:
      - seafile_data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL} 
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD}     # Specifies Seafile admin password, default is 'asecret'.
      - DB_HOST=db
      - DB_ROOT_PASSWD=${SEAFILE_DB_ROOT_PASSWORD}  
      - SEAFILE_SERVER_HOSTNAME=files.${DOMAIN_NAME}
      # - SEAFILE_SERVER_LETSENCRYPT=false
      - TIME_ZONE=${SEAFILE_TIMEZONE}
      - LANG=${SEAFILE_LANG}
      - LANGUAGE=${SEAFILE_LANGUAGE}
      - LC_ALL=${SEAFILE_LC_ALL}
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net
      - ${TRAEFIK_NETWORK_NAME}
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK_NAME}
      
      - traefik.http.routers.seafile.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.seafile.rule=Host(`files.${DOMAIN_NAME}`)

      - traefik.http.routers.seafile_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.seafile_secure.rule=Host(`files.${DOMAIN_NAME}`)
      - traefik.http.routers.seafile_secure.tls.certresolver=le_staging

      - traefik.http.services.seafile.loadbalancer.server.port=80

networks:
  seafile-net:
  ${TRAEFIK_NETWORK_NAME}:
    external: true

volumes:
  seafile_data:
    name: seafile_data
  seafile_mysql:
    name: seafile_mysql