services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_ADMIN_PASSWORD:-password}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      #PGADMIN_CONFIG_CONFIG_DATABASE_URI: "'postgresql://postgres:password@bundes_postgres:5432'"
      PGADMIN_SERVER_JSON_FILE: /servers.json
    ports:
      - 8021:80
    networks:
      - postgres
    depends_on:
      - postgres
    #volumes:
    #  - ./servers.json:/servers.json

  postgres:
    container_name: postgres_default
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    ports:
      - 5555:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - postgres

networks:
  postgres:
    name: postgres
    external: true
