- name: Check if .env file exists
  ansible.builtin.stat:
    path: "{{ n8n.app_directory }}/.env"
  register: env_file

- name: create n8n env file
  ansible.builtin.blockinfile:
    path: "{{ n8n.app_directory }}/.env"
    create: true
    marker: "# {mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      SUB_DOMAIN_NAME={{ n8n.sub_domain_name }}

      POSTGRES_USER={{ secrets.n8n.postgres.admin.user }}
      POSTGRES_PASSWORD={{ secrets.n8n.postgres.admin.password }}
      POSTGRES_DB=n8n
      POSTGRES_NON_ROOT_USER={{ secrets.n8n.postgres.n8n.user }}
      POSTGRES_NON_ROOT_PASSWORD={{ secrets.n8n.postgres.n8n.password }}

      TRAEFIK_ENDPOINT_HTTP_NAME={{ traefik.endpoint.http.name }}
      TRAEFIK_ENDPOINT_HTTPS_NAME={{ traefik.endpoint.https.name }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      TRAEFIK_LETS_ENCRYPT_RESOLVER={{ (mode == "production") | ternary("http_resolver", "http_resolver_staging") }}
  when: not env_file.stat.exists
