version: '3'

services:
  gitlab:
    hostname: gitlab.haex.space
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'gitlab.haex.space'
    ports:
      - 8929:8929
      - 2224:22
    volumes:
      - GITLAB_CONFIG:/etc/gitlab
      - GITLAB_LOGS:/var/log/gitlab
      - GITLAB_DATA:/var/opt/gitlab
    shm_size: 256m
    labels: 
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.gitlab.rule=Host(`gitlab.${HOSTNAME}`)
      - traefik.http.routers.gitlab_secure.rule=Host(`gitlab.${HOSTNAME}`)
      - traefik.http.routers.gitlab_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.gitlab_secure.tls.certresolver=le
      - traefik.http.services.gitlab.loadbalancer.server.port=8929

volumes:
  GITLAB_CONFIG:
  GITLAB_LOGS:
  GITLAB_DATA: