services:
  gitlab:
    hostname: ${SUB_DOMAIN_NAME}.${DOMAIN_NAME}
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    volumes:
      - GITLAB_CONFIG:/etc/gitlab
      - GITLAB_LOGS:/var/log/gitlab
      - GITLAB_DATA:/var/opt/gitlab
    ports:
      - "5080:80"
      - "5022:22"
      - "50433:433"
    networks:
      - web
    shm_size: 256m
    secrets:
      - gitlab_root_password
    configs:
      - source: gitlab
        target: /omnibus_config.rb

    environment:
      #- GITLAB_OMNIBUS_CONFIG = "external_url 'https://gitlab.haex.space/'; gitlab_rails['lfs_enabled'] = true;"
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      #external_url 'https://gitlab.{{ hostname }}'
      #  gitlab_rails['initial_root_password'] = File.read('/run/secrets/gitlab_root_password').gsub("#.*\n$", "").gsub("\n", "")

    labels:
      traefik.enable: true
      traefik.docker.network: ${TRAEFIK_NETWORK_NAME:-proxy}
      traefik.http.routers.gitlab.entrypoints: ${TRAEFIK_ENDPOINT_HTTP_NAME:-web}
      traefik.http.routers.gitlab.rule: Host(`${SUB_DOMAIN_NAME}.${DOMAIN_NAME}`)
      traefik.http.routers.gitlab_secure.rule: Host(`${SUB_DOMAIN_NAME}.${DOMAIN_NAME}`)
      traefik.http.routers.gitlab_secure.entrypoints: ${TRAEFIK_ENDPOINT_HTTPS_NAME:-web_secure}
      traefik.http.routers.gitlab_secure.tls.certresolver: ${TRAEFIK_LETS_ENCRYPT_RESOLVER:-http_resolver_staging}
      traefik.http.services.gitlab_secure.loadbalancer.server.port: 443

volumes:
  GITLAB_CONFIG:
  GITLAB_LOGS:
  GITLAB_DATA:

networks:
  web:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true

secrets:
  gitlab_root_password:
    file: ./root_password.txt

configs:
  gitlab:
    file: ./gitlab.rb
