---
- name: remove env file if exists
  file:
    path: /usr/share/docker/nextcloud/.env
    state: absent

- name: create nextcloud env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/nextcloud/.env
    create: yes
    marker: "# {mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}

      NEXTCLOUD_POSTGRES_IMAGE_NAME={{ nextcloud.postgres.image.name }}
      NEXTCLOUD_POSTGRES_IMAGE_VERSION={{ nextcloud.postgres.image.version }}
      NEXTCLOUD_POSTGRES_DATABASE_NAME={{ nextcloud.postgres.database.name }}
      NEXTCLOUD_POSTGRES_DATABASE_USER={{ nextcloud.postgres.database.user }}
      NEXTCLOUD_POSTGRES_DATABASE_PASSWORD={{ secrets.nextcloud.postgres.password }}

      NEXTCLOUD_REDIS_PASSWORD={{ secrets.nextcloud.redis.password }}
      NEXTCLOUD_REDIS_IMAGE_NAME={{ nextcloud.redis.image.name }}
      NEXTCLOUD_REDIS_IMAGE_VERSION={{ nextcloud.redis.image.version }}

      NEXTCLOUD_ADMIN_PASSWORD={{ secrets.nextcloud.admin.password }}
      NEXTCLOUD_ADMIN_USERNAME={{ nextcloud.admin_username }}
      NEXTCLOUD_HOSTNAME={{ nextcloud.hostname }}
      NEXTCLOUD_IMAGE_NAME={{ nextcloud.image.name }}
      NEXTCLOUD_IMAGE_VERSION={{ nextcloud.image.version }}
      NEXTCLOUD_TIMEZONE={{ nextcloud.timezone }}


      # Backup Variables
      BACKUP_INIT_SLEEP=30m
      BACKUP_INTERVAL=24h
      POSTGRES_BACKUP_PRUNE_DAYS=7
      DATA_BACKUP_PRUNE_DAYS=7
      DATA_BACKUP_NAME=nextcloud-application-backup
      DATA_BACKUPS_PATH=/srv/nextcloud-application-data/backups
      DATA_PATH=/var/www/html
      POSTGRES_BACKUP_NAME=nextcloud-postgres-backup
      POSTGRES_BACKUPS_PATH=/srv/nextcloud-postgres/backups
