---
- block:
    - name: install vim
      apt:
        name: vim
        state: latest

    - name: touch vimrc
      file:
        path: /etc/vim/vimrc
        mode: '0644'
        state: touch

    - name: set vimrc config
      blockinfile:
        path: /etc/vim/vimrc
        marker: '{mark} ansible vim config'
        block: |
          autocmd FileType yaml,yml setlocal ts=2 sts=2 sw=2 et ai expandtab
          let g:indentLine_char = '⦙'
          let g:rehash256 = 1       " Molokai Theme
          set autoindent            " Auto-indent new lines
          set backspace=indent,eol,start  " Backspace behaviour
          set colorcolumn=80
          set cursorcolumn          " Highlight cursor line underneath the cursor vertically.
          set cursorline            " Highlight cursor line underneath the cursor horizontally.
          set expandtab             " Use spaces instead of tabs
          set hlsearch              " Highlight all search results
          set ignorecase            " Always case-insensitive
          set incsearch             " Searches for strings incrementally
          set linebreak             " Break lines at word (requires Wrap lines)
          set number                " Show line numbers
          set ruler                 " Show row and column ruler information
          set shiftwidth=2          " Number of auto-indent spaces
          set showbreak=+++         " Wrap-broken line prefix
          set showcmd               " Show partial command you type in the last line of the screen.
          set showmatch             " Highlight matching brace
          set smartcase             " Enable smart-case search
          set smartindent           " Enable smart-indent
          set smarttab              " Enable smart-tabs
          set softtabstop=2         " Number of spaces per Tab
          set statusline+=%F
          set textwidth=100         " Line wrap (number of cols)
          set undolevels=1000       " Number of undo levels
          set visualbell            " Use visual bell (no beeping)
          set wildmenu              " visual autocomplete for command menu
          syntax on                 " Turn syntax highlighting on.


          setlocal noautoindent
          setlocal nosmartindent

          setlocal indentexpr=g:GetYamlIndent(v:lnum)
          let b:yaml_context = yaml#Context()

          function! g:GetYamlIndent(lnum)
            let l:prevlnum = a:lnum - 1
            let l:prevline = getline(l:prevlnum)
            let l:previndent = indent(l:prevlnum)
            return b:yaml_context.GetNextIndent(l:prevline, l:previndent)
          endfunction

          if !exists('b:undo_indent')
            let b:undo_indent = ''
          endif

          let b:undo_indent .= '| setlocal '.join([
                \ 'tabstop<',
                \ 'softtabstop<',
                \ 'shiftwidth<',
                \])

          syntax match yamlBlockScalarHeader '\zs[|>]\%([+-]\=[1-9]\|[1-9]\=[+-]\)\=\(\s\|$\)'
          highlight link yamlBlockScalarHeader Statement

          syntax match yamlBlockSequenceStart /^\s*-\s*$/
          highlight link yamlBlockSequenceStart Statement
  become: true
