---
- name: check if gitea directory exists
  ansible.builtin.stat:
    path: "{{ gitea.app_directory }}"
  register: gitea_directory

- name: stop and remove gitea container
  block:
    - name: stop gitea container
      community.docker.docker_compose_v2:
        project_src: "{{ gitea.app_directory }}"
        state: absent
      ignore_errors: true

    - name: remove gitea directory
      ansible.builtin.file:
        path: "{{ gitea.app_directory }}"
        state: absent
      ignore_errors: true
  when: gitea_directory.stat.exists and (gitea.from_scratch == true or from_scratch == true)

- name: create app directory
  ansible.builtin.file:
    path: "{{ gitea.app_directory }}"
    state: directory
