---
- name: check if zitadel directory exists
  ansible.builtin.stat:
    path: /usr/share/docker/zitadel
  register: zitadel_directory

- name: remove zitadel folder and env file if exists
  block:
    - name: stop zitadel stack
      community.docker.docker_compose_v2:
        project_src: /usr/share/docker/zitadel
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: /usr/share/docker/zitadel
        state: absent
  when: zitadel_directory.stat.exists and (zitadel.from_scratch == true or from_scratch == true)
