---
- name: prepare zitadel
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - from_scratch.yml
    - create_env_file.yml

- name: place zitadel files in the right directory
  copy:
    src: roles/zitadel/files/
    dest: /usr/share/docker/zitadel/

- name: start zitadel container
  community.docker.docker_compose_v2:
    project_src: /usr/share/docker/zitadel
    state: present
