- name: create directory if not exists
  ansible.builtin.file:
    path: "{{ nocodb.app_directory }}"
    state: directory

- name: copy nocodb files
  ansible.builtin.copy:
    src: roles/nocodb/files/
    dest: "{{ nocodb.app_directory }}"
