---
- name: check if nocodb directory exists
  ansible.builtin.stat:
    path: "{{ nocodb.app_directory }}"
  register: nocodb_directory

- name: stop and remove nocodb container
  block:
    - name: stop nocodb container
      community.docker.docker_compose_v2:
        project_src: "{{ nocodb.app_directory }}"
        state: absent
        remove_volumes: true
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: "{{ nocodb.app_directory }}"
        state: absent
  when: nocodb_directory.stat.exists and (nocodb.from_scratch == true or from_scratch == true)
