version: "3"

services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    hostname: postgresql
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: "true"
      POSTGRESQL_USERNAME: ${KEYCLOAK_DATABASE_USER:-keycloak}
      POSTGRESQL_DATABASE: ${KEYCLOAK_DATABASE_NAME:-keycloak}
      POSTGRESQL_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD:-keycloak}
    volumes:
      - keycloak_postgresql_data:/bitnami/postgresql
    networks:
      - keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:latest
    depends_on:
      postgresql:
        condition: service_started
    hostname: keycloak
    restart: unless-stopped
    ports:
      - 7080:8080
    networks:
      - web
      - keycloak
    environment:
      KEYCLOAK_ADMIN_USER: ${KEYCLOAK_ADMIN_USER:-keycloak}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-keycloak}

      KEYCLOAK_MANAGEMENT_USER: ${KEYCLOAK_MANAGEMENT_USER:-manager}
      KEYCLOAK_MANAGEMENT_PASSWORD: ${KEYCLOAK_MANAGEMENT_PASSWORD:-keycloak}

      KEYCLOAK_ENABLE_HTTPS: "false"
      KEYCLOAK_ENABLE_STATISTICS: "false"

      PROXY_ADDRESS_FORWARDING: "true"
      
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_SCHEMA: ${KEYCLOAK_DATABASE_SCHEMA:-public}
      KEYCLOAK_DATABASE_NAME: ${KEYCLOAK_DATABASE_NAME:-keycloak}
      KEYCLOAK_DATABASE_USER: ${KEYCLOAK_DATABASE_USER:-keycloak}
      KEYCLOAK_DATABASE_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD:-keycloak}
      LANG: de_DE.UTF-8
    labels: 
      traefik.enable: "true"
      traefik.http.routers.keycloak.entrypoints: ${TRAEFIK_HTTP_ENDPOINT}
      traefik.http.routers.keycloak.rule: Host(`keycloak.${HOSTNAME}`)
      traefik.http.routers.keycloak_secure.rule: Host(`keycloak.${HOSTNAME}`)
      traefik.http.routers.keycloak_secure.entrypoints: ${TRAEFIK_HTTPS_ENDPOINT}
      traefik.http.routers.keycloak_secure.tls.certresolver: le_staging
      traefik.http.services.keycloak.loadbalancer.server.port: 7080

networks:
  web:
    external: true
  keycloak:

volumes:
  keycloak_postgresql_data: