- name: Check if .env file exists
  ansible.builtin.stat:
    path: "{{ mattermost.root_directory }}/git_source/.env"
  register: env_file

- name: create mattermost env file from example
  ansible.builtin.copy:
    src: "{{ mattermost.root_directory }}/git_source/env.example"
    dest: "{{ mattermost.root_directory }}/git_source/.env"

- name: set variables in env file
  ansible.builtin.replace:
    path: "{{ mattermost.root_directory }}/git_source/.env"
    regexp: "{{ mattermost_item.regexp }}"
    replace: "{{ mattermost_item.replace }}"
  loop:
    - {
        regexp: "^(DOMAIN=).*",
        replace: "DOMAIN={{ mattermost.sub_domain_name }}.{{ domain_name }}",
      }
    - { regexp: "^(TZ=).*", replace: "TZ={{ mattermost.timezone }}" }
    - {
        regexp: "^(POSTGRES_PASSWORD=).*",
        replace: "POSTGRES_PASSWORD={{ secrets.mattermost.postgres.password }}",
      }
    - {
        regexp: "^(POSTGRES_USER=).*",
        replace: "POSTGRES_USER={{ secrets.mattermost.postgres.user }}",
      }
    - { regexp: "^(POSTGRES_DB=).*", replace: "POSTGRES_DB={{ secrets.mattermost.postgres.db }}" }
    - {
        regexp: "^(POSTGRES_DATA_PATH=).*",
        replace: "POSTGRES_DATA_PATH={{ mattermost.root_directory }}/volumes/database",
      }
    - {
        regexp: "^(MATTERMOST_CONFIG_PATH=).*",
        replace: "MATTERMOST_CONFIG_PATH={{ mattermost.root_directory }}/volumes/config",
      }
    - {
        regexp: "^(MATTERMOST_DATA_PATH=).*",
        replace: "MATTERMOST_DATA_PATH={{ mattermost.root_directory }}/volumes/data",
      }
    - {
        regexp: "^(MATTERMOST_LOGS_PATH=).*",
        replace: "MATTERMOST_LOGS_PATH={{ mattermost.root_directory }}/volumes/logs",
      }
    - {
        regexp: "^(MATTERMOST_PLUGINS_PATH=).*",
        replace: "MATTERMOST_PLUGINS_PATH={{ mattermost.root_directory }}/volumes/plugins",
      }
    - {
        regexp: "^(MATTERMOST_CLIENT_PLUGINS_PATH=).*",
        replace: "MATTERMOST_CLIENT_PLUGINS_PATH={{ mattermost.root_directory }}/volumes/client/plugins",
      }
    - {
        regexp: "^(MATTERMOST_BLEVE_INDEXES_PATH=).*",
        replace: "MATTERMOST_BLEVE_INDEXES_PATH={{ mattermost.root_directory }}/volumes/bleeve-indexes",
      }
  loop_control:
    loop_var: mattermost_item

- name: add variables to env file
  ansible.builtin.blockinfile:
    path: "{{ mattermost.root_directory }}/git_source/.env"
    create: true
    marker: "# {mark} Ansible set environment"
    block: |
      SUB_DOMAIN_NAME={{ mattermost.sub_domain_name }}
  when: not env_file.stat.exists
