---
- name: create authelia env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/authelia/.env
    create: yes
    marker: "#{mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      AUTHELIA_SUB_DOMAIN={{ authelia.sub_domain | default("auth")  }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      TRAEFIK_LETS_ENCRYPT_RESOLVER={{ mode == "production" | ternary("http_resolver", "http_resolver_staging") }}

    # AUTHELIA_JWT_SECRET={{ secrets.authelia.jwt_secret }}
    # AUTHELIA_SESSION_SECRET={{ secrets.authelia.session_secret }}
    # AUTHELIA_STORAGE_ENCRYPTION_KEY={{ secrets.authelia.storage.encryption_key }}
    # AUTHELIA_DEFAULT_REDIRECTION_URL={{ authelia.default_redirection_url }}
    # AUTHELIA_NOTIFIER_SMTP_HOST={{ authelia.notifier.smtp.host }}
    # AUTHELIA_NOTIFIER_SMTP_USERNAME={{ authelia.notifier.smtp.username }}
    # AUTHELIA_NOTIFIER_SMTP_PASSWORD={{ secrets.authelia.smtp.password }}
    # AUTHELIA_NOTIFIER_SMTP_SENDER={{ authelia.notifier.smtp.sender }}

- name: copy authelia config folder
  copy:
    src: roles/authelia/files/config
    dest: /usr/share/docker/authelia/

- name: generate configuration file
  ansible.builtin.template:
    src: roles/authelia/files/configuration.j2
    dest: /usr/share/docker/authelia/config/configuration.yml

- name: place authelia docker-compose file in the right directory
  copy:
    src: roles/authelia/files/docker-compose.yml
    dest: /usr/share/docker/authelia/docker-compose.yml

- name: start authelia container
  community.docker.docker_compose_v2:
    project_src: /usr/share/docker/authelia
    state: present
