---
- name: create vaultwarden env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/vaultwarden/.env
    create: yes
    marker: "#{mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      VAULTWARDEN_PORT={{ vaultwarden.port }}
      VAULTWARDEN_ADMIN_TOKEN={{ secrets.vaultwarden.admin_token }}
      VAULTWARDEN_IMAGE_VERSION={{ vaultwarden.image.version }}

- name: place vaultwarden docker-compose file in the right directory
  copy:
    src: roles/vaultwarden/files/
    dest: /usr/share/docker/vaultwarden/

- name: start vaultwarden container
  community.docker.docker_compose_v2:
    project_src: /usr/share/docker/vaultwarden
    state: present
