---
- name: check if portainer directory exists
  ansible.builtin.stat:
    path: '{{ portainer.app_directory }}'
  register: portainer_directory

- name: stop and remove portainer container
  block:
    - name: stop portainer container
      community.docker.docker_compose_v2:
        project_src: '{{ portainer.app_directory }}'
        state: absent
      ignore_errors: true

    - name: remove portainer directory
      ansible.builtin.file:
        path: '{{ portainer.app_directory }}'
        state: absent
  when: portainer_directory.stat.exists and (portainer.from_scratch == true or from_scratch == true)

- name: create app directory
  ansible.builtin.file:
    path: '{{ portainer.app_directory }}'
    state: directory
