- name: prepare portainer for {{ mode }}
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - from_scratch.yml
    - copy_files.localhost.yml
    - create_env_file.localhost.yml
    - start_container.yml
  when: mode == "localhost"

- name: prepare portainer for {{ mode }}
  ansible.builtin.include_tasks: '{{ item }}'
  loop:
    - from_scratch.yml
    - copy_files.yml
    - create_env_file.yml
    - start_container.yml
  when: mode != "localhost"
