version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    domain_name: keycloak
    ports:
      - 7080:8080
    networks:
      - ${TRAEFIK_NETWORK_NAME}
      - ${KEYCLOAK_NETWORK_NAME}
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin 
      - KEYCLOAK_HOSTNAME_STRICT_HTTPS=false
    command:
      - start-dev --domain_name keycloak.${DOMAIN_NAME} --domain_name-port=7080  
    labels: 
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.keycloak.rule=Host(`keycloak.${DOMAIN_NAME}`)
      - traefik.http.routers.keycloak_secure.rule=Host(`keycloak.${DOMAIN_NAME}`)
      - traefik.http.routers.keycloak_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.keycloak_secure.tls.certresolver=le_staging
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

networks:
  ${TRAEFIK_NETWORK_NAME}:
    external: true
  ${KEYCLOAK_NETWORK_NAME}:
    external: true
      