version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    hostname: keycloak
    ports:
      - 7080:8080
    networks:
      - web
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin 
      - KEYCLOAK_HOSTNAME_STRICT_HTTPS=false
    command:
      - start-dev --hostname keycloak.${HOSTNAME} --hostname-port=7080  
    labels: 
      - traefik.enable=true
      - traefik.http.routers.keycloak.entrypoints=${TRAEFIK_HTTP_ENDPOINT}
      - traefik.http.routers.keycloak.rule=Host(`keycloak.${HOSTNAME}`)
      - traefik.http.routers.keycloak_secure.rule=Host(`keycloak.${HOSTNAME}`)
      - traefik.http.routers.keycloak_secure.entrypoints=${TRAEFIK_HTTPS_ENDPOINT}
      - traefik.http.routers.keycloak_secure.tls.certresolver=le_staging
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

networks:
  web:
    external: true
      