#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA $KEYCLOAK_DATABASE_SCHEMA;

	CREATE USER $KEYCLOAK_DATABASE_USER with PASSWORD '$KEYCLOAK_DATABASE_PASSWORD';

	CREATE DATABASE $KEYCLOAK_DATABASE_NAME;

	GRANT ALL PRIVILEGES ON DATABASE $KEYCLOAK_DATABASE_NAME TO $KEYCLOAK_DATABASE_USER;

EOSQL