services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer_data:/data
    ports:
      - 19443:9443
      - 19000:9000
      - 18000:8000

    command: --admin-password ${ADMIN_PASSWORD} --log-level DEBUG

volumes:
  portainer_data:
    name: portainer_data
