version: "3"

services:
  portainer:
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /run/podman/podman.sock:/var/run/docker.sock:Z
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer_data:/data
    networks:
      - traefik
    ports:
      - 127.0.0.1:19443:9443
      - 127.0.0.1:19000:9000
      - 127.0.0.1:18000:8000
    labels:
      traefik.enable: "true"
      traefik.docker.network: ${TRAEFIK_NETWORK_NAME:-proxy}
      traefik.http.routers.portainer.entrypoints: ${TRAEFIK_HTTP_ENDPOINT}
      traefik.http.routers.portainer.rule: Host(`portainer.${DOMAIN_NAME}`)
      traefik.http.routers.portainer_secure.rule: Host(`portainer.${DOMAIN_NAME}`)
      traefik.http.routers.portainer_secure.entrypoints: ${TRAEFIK_HTTPS_ENDPOINT}
      traefik.http.routers.portainer_secure.tls.certresolver: http_resolver_staging
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    command: --admin-password ${ADMIN_PASSWORD}

volumes:
  portainer_data:
    name: portainer_data

networks:
  traefik:
    name: ${TRAEFIK_NETWORK_NAME:-proxy}
    external: true
