- name: Check if .env file exists
  ansible.builtin.stat:
    path: /usr/share/docker/oauth-proxy/.env
  register: env_file

- name: create oauth-proxy env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/oauth-proxy/.env
    create: true
    marker: "# {mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      TRAEFIK_ENDPOINT_HTTP_NAME={{ traefik.endpoint.http.name }}
      TRAEFIK_ENDPOINT_HTTPS_NAME={{ traefik.endpoint.https.name }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      TRAEFIK_LETS_ENCRYPT_RESOLVER={{ (mode == "production") | ternary("http_resolver", "http_resolver_staging") }}
  when: not env_file.stat.exists or oauth_proxy.from_scratch == true or from_scratch == true
