---
- name: remove env file if exists
  ansible.builtin.file:
    path: /usr/share/docker/traefik/.env
    state: absent

- name: create network
  include_tasks:
    file: create_network.yml

- name: create traefik env file
  include_tasks:
    file: create_env_file.yml

- name: place traefik docker-compose file in the right directory
  copy:
    src: roles/traefik/files/docker-compose.yml
    dest: /usr/share/docker/traefik/docker-compose.yml

- name: start traefik container
  community.docker.docker_compose:
    project_src: /usr/share/docker/traefik/
    state: present
    nocache: yes
