---
- name: create traefik config file
  blockinfile:
    path: /etc/traefik/traefik.yml
    create: true
    marker: "# {mark} Ansible set config"
    block: |
      api:
        dashboard: true

      metrics:
        prometheus:
          addRoutersLabels: true

      certificatesResolvers:
        http_resolver:
          acme:
            email: "{{ traefik.lets_encrypt.email }}"
            storage: "{{ traefik.lets_encrypt.storage.http_resolver | default(acme_letsencrypt.json) }}"
            httpChallenge:
              entryPoint: {{ traefik.http_endpoint }}
        
        http_resolver_staging:
          acme:
            caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
            email: "{{ traefik.lets_encrypt.email }}"
            storage: "{{ traefik.lets_encrypt.storage.http_resolver | default(acme_letsencrypt.json) }}"
            httpChallenge:
              entryPoint: {{ traefik.http_endpoint }}

        tls_resolver:
          acme:
            email: "{{ traefik.lets_encrypt.email }}"
            storage: "{{ traefik.lets_encrypt.storage.tls_resolver | default(tls_letsencrypt.json) }}"
            tlsChallenge: {}
            
      entryPoints:
        ping:
          address: ':88'
        {{ traefik.http_endpoint }}:
          address: ':80'
          http:
          #  redirections:
          #    entryPoint:
          #      to: {{ traefik.https_endpoint }}
          #      scheme: https

        {{ traefik.https_endpoint }}:
          address: ':443'
          http:

      ping:
        entryPoint: "ping"

      global:
        checkNewVersion: true
        sendAnonymousUsage: false

      providers:
        docker:
          endpoint: "unix:///var/run/docker.sock"
          exposedByDefault: false
          network: "{{ traefik.network_name }}"
        file:
          filename: "./dynamic_conf.yml"
          watch: true
        providersThrottleDuration: 10s

      log:
        level: "INFO"
        filePath: "/var/log/traefik/traefik.log"
      accessLog:
        filePath: "/var/log/traefik/access.log"
        bufferingSize: 100
