---
- name: create letsencrypt acme json
  ansible.builtin.file:
    mode: "600"
    path: /usr/share/docker/traefik/acme_letsencrypt.json
    state: touch

- name: create letsencrypt tls json
  ansible.builtin.file:
    mode: "600"
    path: /usr/share/docker/traefik/tls_letsencrypt.json
    state: touch
