---
- name: create traefik network
  community.docker.docker_network:
    name: '{{ traefik.network_name }}'

- name: create keycloak network
  community.docker.docker_network:
    name: '{{ keycloak.network_name }}'