---
- name: create traefik network
  community.docker.docker_network:
    name: ${TRAEFIK_NETWORK_NAME:-traefik}

- name: create keycloak network
  community.docker.docker_network:
    name: ${KEYCLOAK_NETWORK_NAME:-keycloak}