---
- name: remove env file if exists
  ansible.builtin.file:
    path: /usr/share/docker/traefik/.env
    state: absent

- name: create traefik env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/traefik/.env
    create: yes
    marker: "# {mark} Ansible set environment"
    block: |
      DOMAIN_NAME={{ domain_name }}
      COMPOSE_PROJECT_NAME=traefik
      AUTHELIA_SUB_DOMAIN={{ authelia.sub_domain | default("auth")  }}
      TRAEFIK_SUB_DOMAIN={{ traefik.sub_domain | default("traefik") }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}
      TRAEFIK_PING_PORT={{ traefik.ping_port }}
      TRAEFIK_HTTP_PORT={{ traefik.http_port }}
      TRAEFIK_HTTPS_PORT={{ traefik.https_port }}

      # Lets Encrypt
      TRAEFIK_LETS_ENCRYPT_EMAIL={{ traefik.lets_encrypt.email }}
      TRAEFIK_LETS_ENCRYPT_RESOLVER={{ (mode == "production") | ternary("http_resolver", "http_resolver_staging") }}
      TRAEFIK_LETS_ENCRYPT_STORAGE_HTTP_RESOLVER={{ traefik.lets_encrypt.storage.http_resolver }}
      TRAEFIK_LETS_ENCRYPT_STORAGE_TLS_RESOLVER={{ traefik.lets_encrypt.storage.tls_resolver }}

      # Service Traefik
      TRAEFIK_CONTAINER_NAME={{ traefik.container_name | default(traefik) }}
      TRAEFIK_HOSTNAME={{ traefik.hostname | default(traefik) }}
      TRAEFIK_IMAGE={{ traefik.image | default(traefik) }}
      TRAEFIK_IMAGE_VERSION={{ traefik.image_version | default(latest) }}
