---
- name: check traefik directory
  ansible.builtin.stat:
    path: '{{ traefik.app_directory }}'
  register: traefik_directory

- name: stop traefik and remove folder if it exists
  block:
    - name: stop traefik container
      community.docker.docker_compose_v2:
        project_src: '{{ traefik.app_directory }}'
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: '{{ traefik.app_directory }}'
        state: absent
  when: traefik_directory.stat.exists and (traefik.from_scratch == true or from_scratch == true)
