---
- name: create keycloak env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/keycloak/.env
    create: yes
    marker: '# {mark} Ansible set environment'
    block: |
      HOSTNAME={{ hostname }}
      COMPOSE_PROJECT_NAME=keycloak

      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}

      ADMIN_USER={{ keycloak.admin_user }}
      ADMIN_PASSWORD={{ secrets.keycloak.admin_password }}

      POSTGRESQL_PASS={{ secrets.keycloak.postgres_password}}
      POSTGRESQL_USER={{ keycloak.postgres_user }}



- name: place keycloak files in the right directory
  copy:
    src: roles/keycloak/files/
    dest: /usr/share/docker/keycloak/
    
- name: start keycloak container
  community.docker.docker_compose:
    project_src: /usr/share/docker/keycloak
    state: present