---
- name: create cos env file
  ansible.builtin.blockinfile:
    path: /usr/share/docker/cos/.env
    create: yes
    marker: '#{mark} Ansible set environment'
    block: |
      DOMAIN_NAME={{ domain_name }}
      TRAEFIK_HTTP_ENDPOINT={{ traefik.http_endpoint }}
      TRAEFIK_HTTPS_ENDPOINT={{ traefik.https_endpoint }}
      TRAEFIK_NETWORK_NAME={{ traefik.network_name }}

- name: place cos files in the right directory
  copy:
    src: roles/cos/files/
    dest: /usr/share/docker/cos/
    
- name: start cos container
  community.docker.docker_compose:
    project_src: /usr/share/docker/cos
    state: present
    build: yes
    nocache: yes