services:
  vaultwarden:
    image: vaultwarden/server:${VAULTWARDEN_IMAGE_VERSION:-latest}
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - ${VAULTWARDEN_PORT}:80
    networks:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - vaultwarden_data:/data/
      - vaultwarden_log:/var/log/vaultwarden
    environment:
      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}
      RUST_BACKTRACE: 1
      LOG_FILE: /var/log/vaultwarden/vaultwarden.log
      WEBSOCKET_ENABLED: true
      DOMAIN: https://vault.${DOMAIN_NAME}
      DOMAIN_ORIGIN: https://vault.${DOMAIN_NAME}
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: ${TRAEFIK_HTTPS_ENDPOINT}
      traefik.http.routers.vaultwarden.rule: Host(`vault.${DOMAIN_NAME}`)
      traefik.http.routers.vaultwarden.tls: true
      traefik.http.routers.vaultwarden.tls.certresolver: ${TRAEFIK_LETS_ENCRYPT_RESOLVER:-http_resolver_staging}
      traefik.http.routers.vaultwarden.service: vaultwarden
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.docker.network: traefik
      #traefik.http.routers.vaultwarden.middlewares: authelia@docker

volumes:
  vaultwarden_data:
  vaultwarden_log:

networks:
  traefik:
    name: ${TRAEFIK_NETWORK}
    external: true
