- name: create directory if not exists
  ansible.builtin.file:
    path: '{{ postgres.app_directory }}'
    state: directory

- name: copy postgres files
  ansible.posix.synchronize:
    src: roles/postgres/files/
    dest: '{{ postgres.app_directory }}'
    recursive: true
