---
- name: check if postgres directory exists
  ansible.builtin.stat:
    path: "{{ postgres.app_directory }}"
  register: postgres_directory

- name: stop and remove postgres container
  block:
    - name: stop postgres container
      community.docker.docker_compose_v2:
        project_src: "{{ postgres.app_directory }}"
        state: absent
      ignore_errors: true

    - name: remove postgres network
      community.docker.docker_network:
        name: postgres
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: "{{ postgres.app_directory }}"
        state: absent
  when: postgres_directory.stat.exists and (postgres.from_scratch == true or from_scratch == true)

- name: create postgres network
  community.docker.docker_network:
    name: postgres
    state: present
    attachable: yes
