---
- name: check if kratos directory exists
  ansible.builtin.stat:
    path: /usr/share/docker/kratos
  register: kratosDirectory

- name: shutdown and remove kratos completly
  block:
    - name: stop kratos stack
      community.docker.docker_compose_v2:
        project_src: /usr/share/docker/kratos
        state: absent
      ignore_errors: true

    - name: remove directory
      ansible.builtin.file:
        path: /usr/share/docker/kratos/
        state: absent

  when: kratosDirectory.stat.exists and (kratos.from_scratch == true or from_scratch == true)
