- name: prepare kratos
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - from_scratch.yml
    - create_env_file.yml

- name: copy kratos config folder
  ansible.builtin.copy:
    src: roles/kratos/files/kratos/config/
    dest: /usr/share/docker/kratos/config/

- name: create kratos config from jinja
  ansible.builtin.template:
    src: roles/kratos/files/kratos/kratos.yml.j2
    dest: /usr/share/docker/kratos/config/kratos.yml

- name: copy oathkeeper config folder
  ansible.builtin.copy:
    src: roles/kratos/files/oathkeeper/
    dest: /usr/share/docker/kratos/oathkeeper/

- name: create access rules config from jinja
  ansible.builtin.template:
    src: roles/kratos/files/oathkeeper/access-rules.yml.j2
    dest: /usr/share/docker/kratos/oathkeeper/access-rules.yml

- name: place kratos docker-compose file in the right directory
  ansible.builtin.copy:
    src: roles/kratos/files/docker-compose.yml
    dest: /usr/share/docker/kratos/docker-compose.yml

- name: start kratos container
  community.docker.docker_compose_v2:
    project_src: /usr/share/docker/kratos
    state: present
